### ISSUE TITLE
not download sources to build

### ISSUE THREAD

**Issue by ukoz** [streamlink/streamlink-portable#22] opened 2018-03-27 16:38 UTC
Open program, select any of 3 options (ie portable EXE)
then select any of 3 next options (ie latest snapshot, or custom and paste "https://github.com/streamlink/streamlink/archive/master.zip")
"Download source" fail "Step 2 - Error"
pasting "https://github.com/streamlink/streamlink/archive/master.zip" in browser do start download.

**Comment by ukoz** [comment] 2018-03-27 17:57
temp fix is to download
https://github.com/cesanta/mongoose
and put pre-downloaded "https://github.com/streamlink/streamlink/archive/master.zip" on it
then use "custom" option to streamlink-portable

**Comment by Vangelis66** [comment] 2018-03-27 21:18
@ukoz 

Can't reproduce here... What is your exact OS version, architecture bitness and .NET Framework version?
FYI, my old system does not even meet current minimum requirements, but I was successful in compiling latest "nightly" portable build... 

**OS**: Windows Vista SP2 32-bit, all MS updates until April 2017 (official EOL), after that manual install of security updates meant for Windows Server 2008 SP2 32-bit (same NT 6.0 kernel... ); one of these "post-EOL" MS updates adds TLS v1.2 support to Vista's Schannel...

**.NET Framework 4 family**: 4.6.1 (not officially supported, but the last of the 4.x.x family to install on Vista SP2)

 I downloaded latest code snapshot of this repo (at the time of writing `git-20180309-g2a4d81b`), followed instructions to the letter and successfully compiled Portable EXE of `streamlink-0.11.0-31-20180327-ge64f105`, the latest snapshot of the streamlink repo...

Inside './files/TEMP` dir I did find archive `Streamlink_Latest.zip` (as expected), but just to humour you I deleted it and started anew with your steps-to-reproduce (Portable EXE -> Custom -> pasting [master.zip](https://github.com/streamlink/streamlink/archive/master.zip)); I had no error while downloading source, compilation succeeded: 

![sl](https://user-images.githubusercontent.com/9669492/37995245-6a41e75c-321c-11e8-9b81-250f4c3dbd39.jpg)
![success](https://user-images.githubusercontent.com/9669492/37995256-779350bc-321c-11e8-838d-4d3480477bfa.jpg)

Your issue, without further detais, appears to be related to either a network error, write permissions or overzealous anti-virus suite (???) ...

**Comment by Lord-Nightmare** [comment] 2018-03-27 23:13
I'm having a similar problem here, it started about 2 weeks ago.
I did a fresh git reset --hard HEAD of the local tree to clear out any temp files, and then ran the "Streamlink for Windows.exe" in the streamlink-portable\Streamlink for Windows (Compiled) directory.

What happens is such:
* Step 1/3 (the 3 options to click, and I click 'Standalone EXE')
* Step 2/3 (I click 'latest snapshot')
* It shows 'Step 2: Loading 1/1'
* then 'Step 2: downloading(x%)'
* then 'Step 3: Loading (1/3)'
* then it displays 'Step 3: Error'

clicking the retry arrow goes back to the 'Step 3: Loading (1/3)' step but doesn't achieve anything different.
I can't find any sort of log file which would explain the exact error occuring here, either.

OS: Windows 10 Pro x64, version 1709, build 16299.309

**Comment by RosadinTV** [comment] 2018-03-28 11:36
Tried both bugs but can't reproduce them.
I will add an error logger in the next revision so we can determine the origin.

**Comment by RosadinTV** [comment] 2018-03-28 13:49
Done, now you can download the new compiler and paste the error here.

**Comment by Lord-Nightmare** [comment] 2018-03-30 08:04
I downloaded the latest compiler, tried it, and it works fine with no errors. I have no idea what was causing that error I ran into, I'm confused too.

**Comment by RosadinTV** [comment] 2018-03-30 10:18
There is only one explanation 😆 
![image](https://user-images.githubusercontent.com/13382316/38134675-842ec264-33ea-11e8-9a74-35c0f7df3e51.png)

**Comment by ukoz** [comment] 2018-04-18 11:36
still error for me
`System.NullReferenceException: Object reference not set to an instance of an object.
   at Streamlink_for_Windows.MainWindow.GetPageHTMLCustom(String URL, String UserAgent_Custom, String Referer_Custom, String Cookies)
   at Streamlink_for_Windows.MainWindow.BW_STEPS_DoWork(Object sender, DoWorkEventArgs e)`

**Comment by Lord-Nightmare** [comment] 2018-04-22 06:39
Interestingly enough, on my other machine, which runs windows 7 x64, I get the same error as ukoz does. So this issue is not dead.

**Comment by Lord-Nightmare** [comment] 2018-04-22 07:00
Almost (but not quite) sure I figured out the problem: On windows 7, I think the visual basic runtime doesn't support tls 1.2 for HTTPS connections, and github requires those since 20180208, see https://developer.github.com/changes/2018-02-01-weak-crypto-removal-notice/ and https://githubengineering.com/crypto-deprecation-notice/

If my guess is correct, I don't believe this is a problem streamlink-portable can fix, unless the downloader is changed to use its own https library.

If you manualy host the streamlink-master.zip file elsewhere and it does support unencrypted HTTP or TLS 1.1 (as of writing, dropbox does this), it will download and build correctly.

**Comment by RosadinTV** [comment] 2018-04-22 10:15
Thanks for the status update guys.
I'll fix it soon. :hammer_and_wrench:

**Comment by RosadinTV** [comment] 2018-04-23 02:27
@ukoz @Lord-Nightmare 
It should be fixed in the latest version 🍰

**Comment by Lord-Nightmare** [comment] 2018-04-23 14:11
It is fixed in the latest version (at least for me), thanks!

**Comment by RosadinTV** [comment] 2018-04-24 01:41
@Vangelis66 
As you and @Lord-Nightmare said, the problem was TLS v1.2.

.NET Framework supports TLS v1.2 but not in every case:
**3.5 or bellow**: Not supported.
**4.0**: Not direct support.
**4.5**: Supported but not enabled by default.
**4.6 or later**: Supported and enabled by default.

The app target is .NET Framework 4.7 but can also run with older Frameworks (like 4.5) because of Microsoft backward compatibility policy.
So, the solution was update the docs stating 4.5 as the minimum version and enabling the protocol for this Framework ([#](https://github.com/streamlink/streamlink-portable/blob/ec871b6625dae33caab988d92715e90355cd64dd/Streamlink%20for%20Windows%20(Source%20code)/MainWindow.xaml.vb#L41)).
With this info we can assume that Lord-Nightmare and ukoz have 4.5 installed.

PS: Sorry for my bad English, hope you can understand what i meant. 😆 
And thank you for your interest in this project 😃

**Comment by RosadinTV** [comment] 2018-05-23 11:26
@ukoz
Can we close this issue?

**Closed** 2018-06-28 17:23 UTC
